// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fibonacci(n) {
  let next,
    prev,
    i = 0,
    j = 0,
    accumulated = 0,
    sequence = [1];

  for (i; i < n; i++) {
    if (i === 0) {
      sequence.push(sequence[i] + 1);
    } else if (sequence[i] < n) {
      prev = sequence[i - 1];
      next = prev + sequence[i];

      if (next > n) break;

      sequence.push(next);
    }
  }

  for (j; j < sequence.length; j++) {
    if (sequence[j] % 2 === 0) {
      accumulated = accumulated + sequence[j];
    }
  }

  return accumulated;
}

fibonacci(4000000);
